# Generated by Django 5.1.6 on 2025-02-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('name__iexact', models.F('name'))), fields=('name',), name='unique_category_name_case_insensitive'),
        ),
    ]
