# Generated by Django 5.1.6 on 2025-02-25 13:35

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_unique_category_name_case_insensitive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
